# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.CharField(max_length=250)),
                ('akash', models.TextField()),
                ('ayush', models.TextField()),
                ('ronak', models.TextField()),
                ('raghav', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='overall_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akash', models.IntegerField()),
                ('ayush', models.IntegerField()),
                ('ronak', models.IntegerField()),
                ('raghav', models.IntegerField()),
                ('house', models.IntegerField()),
            ],
        ),
    ]
