# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_match_status_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_status',
            name='date',
        ),
    ]
