# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_match_status_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_status',
            name='match_teams',
            field=models.TextField(default=''),
        ),
    ]
