# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_match_status_iscalculated'),
    ]

    operations = [
        migrations.CreateModel(
            name='points_scored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('match_number', models.IntegerField()),
                ('akash', models.TextField(default=',,,,')),
                ('ayush', models.TextField(default=',,,,')),
                ('ronak', models.TextField(default=',,,,')),
                ('raghav', models.TextField(default=',,,,')),
                ('isCalculated', models.BooleanField(default=False)),
            ],
        ),
    ]
