# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_auto_20170404_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_status',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='overall_status',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='points_scored',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
