# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_auto_20170404_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='points_scored',
        ),
    ]
